// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPbE0sMd6OdUZ8Vi7GO4xuy0TmTSylFZs',
    appId: '1:862575476926:ios:39371255ac11ecde491eef',
    messagingSenderId: '862575476926',
    projectId: 'mh-meir-movies',
    authDomain: 'mh-meir-movies-default-rtdb.firebaseio.com/',
    databaseURL: 'https://mh-meir-movies-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://mh-meir-movies.firebasestorage.app/',
    measurementId: 'G-8BQCS5F026',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbE0sMd6OdUZ8Vi7GO4xuy0TmTSylFZs',
    appId: '1:862575476926:ios:39371255ac11ecde491eef',
    messagingSenderId: '862575476926',
    projectId: 'mh-meir-movies',
    authDomain: 'mh-meir-movies-default-rtdb.firebaseio.com/',
    databaseURL: 'https://mh-meir-movies-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://mh-meir-movies.firebasestorage.app/',
    measurementId: 'G-8BQCS5F026',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPbE0sMd6OdUZ8Vi7GO4xuy0TmTSylFZs',
    appId: '1:862575476926:ios:39371255ac11ecde491eef',
    messagingSenderId: '862575476926',
    projectId: 'mh-meir-movies',
    authDomain: 'mh-meir-movies-default-rtdb.firebaseio.com/',
    databaseURL: 'https://mh-meir-movies-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://mh-meir-movies.firebasestorage.app/',
    measurementId: 'G-8BQCS5F026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPbE0sMd6OdUZ8Vi7GO4xuy0TmTSylFZs',
    appId: '1:862575476926:ios:39371255ac11ecde491eef',
    messagingSenderId: '862575476926',
    projectId: 'mh-meir-movies',
    authDomain: 'mh-meir-movies-default-rtdb.firebaseio.com/',
    databaseURL: 'https://mh-meir-movies-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://mh-meir-movies.firebasestorage.app/',
    measurementId: 'G-8BQCS5F026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPbE0sMd6OdUZ8Vi7GO4xuy0TmTSylFZs',
    appId: '1:862575476926:ios:39371255ac11ecde491eef',
    messagingSenderId: '862575476926',
    projectId: 'mh-meir-movies',
    authDomain: 'mh-meir-movies-default-rtdb.firebaseio.com/',
    databaseURL: 'https://mh-meir-movies-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://mh-meir-movies.firebasestorage.app/',
    measurementId: 'G-8BQCS5F026',
  );
}
