// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiV7KTQWa6u2BFl-Cox5ZKOy3-QY1dPhY',
    appId: '1:257753299659:android:009dd870093fcaa7e0f94e',
    messagingSenderId: '923589936774',
    projectId: 'meirhemed-mhnotes',
    authDomain: 'meirhemed-mhnotes.firebaseapp.com',
    databaseURL: 'https://mhnotes-meirhemed-default-rtdb.firebaseio.com',
    storageBucket: 'meirhemed-mhnotes.appspot.com',
    measurementId: 'G-8BQCS5F026',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9IZhZGecEs15tMHZfJPYY3HJtCSb6bKg',
    appId: '1:923589936774:android:362b633d258ced07cd7307',
    messagingSenderId: '923589936774',
    projectId: 'meirhemed-mhnotes',
    databaseURL: 'https://meirhemed-mhnotes-default-rtdb.firebaseio.com',
    storageBucket: 'meirhemed-mhnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLNsTZBcIRoC-L1oYIZDdnwL-j4UYA2AA',
    appId: '1:257753299659:ios:d273d009d5040c2ae0f94e',
    messagingSenderId: '923589936774',
    projectId: 'meirhemed-mhnotes',
    databaseURL: 'https://meirhemed-mhnotes-default-rtdb.firebaseio.com',
    storageBucket: 'meirhemed-mhnotes.appspot.com',
    iosBundleId: 'com.meirhemed.mhnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLNsTZBcIRoC-L1oYIZDdnwL-j4UYA2AA',
    appId: '1:923589936774:ios:93c6f27ddf6bbebecd7307',
    messagingSenderId: '923589936774',
    projectId: 'meirhemed-mhnotes',
    databaseURL: 'https://meirhemed-mhnotes-default-rtdb.firebaseio.com',
    storageBucket: 'meirhemed-mhnotes.appspot.com',
    iosBundleId: 'com.meirhemed.mhnotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiV7KTQWa6u2BFl-Cox5ZKOy3-QY1dPhY',
    appId: '1:923589936774:web:178867ef8ab0fc6ccd7307',
    messagingSenderId: '923589936774',
    projectId: 'meirhemed-mhnotes',
    authDomain: 'meirhemed-mhnotes.firebaseapp.com',
    databaseURL: 'https://meirhemed-mhnotes-default-rtdb.firebaseio.com',
    storageBucket: 'meirhemed-mhnotes.appspot.com',
    measurementId: 'G-LGM25DV2TE',
  );
}
